### ISSUE TITLE
Screens version 10.0.

### ISSUE THREAD

**Issue by imring** [imring/spur-imgui#1]
I provide screenshots from the 10th version of the spur.
![image](https://user-images.githubusercontent.com/35897995/39663977-ca84f6e6-5084-11e8-9114-1b27835e670f.png)
![image](https://user-images.githubusercontent.com/35897995/39663979-da5a5d04-5084-11e8-8c69-4c8f709673c7.png)

**Comment by rraggerr** [comment]
ещкере

**Comment by imring** [comment]
![image](https://user-images.githubusercontent.com/35897995/39664535-42bd99bc-508d-11e8-9db5-c2c06112f380.png)
![image](https://user-images.githubusercontent.com/35897995/39664537-4b4e4770-508d-11e8-8827-53dafafe94ed.png)

**Comment by rraggerr** [comment]
ты чо ахуел удалять?

**Comment by AnWuPP** [comment]
Не выравнил текст с фреймом.

**Comment by imring** [comment]
@DonHomka где?

**Comment by imring** [comment]
![image](https://user-images.githubusercontent.com/35897995/63357176-a9436d80-c371-11e9-89e7-1b39daa94c40.png)
Released.
